CREATE TABLE IF NOT EXISTS USER (
	USER_ID IDENTITY,
	USER_NAME VARCHAR(30) NOT NULL,
	USER_PASSWORD VARCHAR(256) NOT NULL,
);

CREATE TABLE IF NOT EXISTS ROLE (
	ROLE_ID IDENTITY,
	ROLE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
	USER_ROLE_ID IDENTITY,
	USER_ID NUMBER NOT NULL,
	ROLE_ID NUMBER NOT NULL
);